### ISSUE TITLE
Retrieve packages from mason-binaries on S3 

### ISSUE THREAD

**Issue by millzpaugh** [mapbox/mason-js#1]
## Phase 1 - Read, Retrieve, and Symlink
Create an initial script that: 
- [x] Reads mason-versions.ini file
- [x] Retrieves header-only and binary packages from S3 and downloads them locally into the `mason-packages` directory 
- [x] Symlinks packages in the `.link` folder
