### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason-js#35]
@millzpaugh this is a proposal for steps to release:

 - [x] Create an alpha release (add `0.0.1-alpha` to the `package.json` version) and run `npm publish`: https://www.npmjs.com/package/mason-js-sdk
 - [x] Test integrating into https://github.com/mapbox/node-cpp-skel and https://github.com/mapbox/vtquery, create PRs/branches for both to ensure `mason-js` works correctly (https://github.com/mapbox/node-cpp-skel/compare/proposed-mason-js-port can be used as a guide but might need updates). Get help from the team on these ports where you get stuck.
      - [x] node-cpp-skel PR: https://github.com/mapbox/node-cpp-skel/pull/111
      - [x] vtquery PR: https://github.com/mapbox/vtquery/pull/67
 - [x] Ask for PR review on the vtquery/node-cpp-skel PRs from the @mapbox/core-tech team.
 - [x] After Prs look good, change the version back to `0.1.0` in package.json
 - [x] Publish!
 - [x] Also create a `git tag`
 - [x] Head back to the vtquery/node-cpp-skel branches and point them at the formal release
 - [ ] Merge those PRs

**Comment by millzpaugh** [comment]
@springmeyer This is looking good...except for the failing `make tidy` command. I added `mason-js` to the `clang-tidy.sh`, but it's still erroring - the mason-js install of `clang` seems to alter `module.cpp`, causing an error. 

**Before** 

``` void init(v8::Local<v8::Object> **target**) {
    // expose helloAsync method
    Nan::SetMethod(target, "vtquery", VectorTileQuery::vtquery);
}
```

**After**
``` void init(v8::Local<v8::Object> **/*target*/**) {
    // expose helloAsync method
    Nan::SetMethod(target, "vtquery", VectorTileQuery::vtquery);
}
```
Any ideas?

**Comment by springmeyer** [comment]
Excellent work on this @millzpaugh. I'm poking at vtquery and things are looking good - feeling like `mason-js` is ready for release and its just a matter of how to use it in vtquery that needs work.

**Comment by springmeyer** [comment]
> feeling like mason-js is ready for release and it's just a matter of how to use it in vtquery that needs work.

Actually, just hit something that I think needs fixed in mason-js. @millzpaugh have a read of https://github.com/mapbox/vtquery/pull/68#issuecomment-371993993 on monday and let me know what you think.

**Comment by millzpaugh** [comment]
@springmeyer I'm wondering if the node-cpp-skel & vtquery branches are ready to be merged? Or should I start working on #46 first?

**Comment by springmeyer** [comment]
Per voice with @millzpaugh - the last thing here is to tag a new release with https://github.com/mapbox/mason-js/pull/48 and one more downstream test of installing vtquery based on this release.

**Comment by springmeyer** [comment]
We're good here / released 🎉
