### ISSUE TITLE
Overview - Phases 1 & 2

### ISSUE THREAD

**Issue by millzpaugh** [mapbox/mason-js#5]
# The history behind mason & mason-js 

Mason was created because at the time there was:

- No existing cross-platform binary distribution
- No existing consistent way to build from source (so many build systems)
- No way to build/compile binaries in C++11 mode on linux (at the time)
- node-pre-gyp had been proven in production for node addon binaries, now we needed something for C++

Mason now exists and supports both header-only C++ libs and precompiled packages (binaries), such as C libraries (e.g. libpng), C++ libraries (libboost), and Command line tools (osmium-tool).
Each package has a `mason.ini` file that provides metadata about the package. 

**mason.ini**

    name=vtzero
    version=556fac5
    header_only=true
    include_dirs={prefix}/include

Now that mason is widely used, [there’s an increasing demand for a standalone cross-platform client](https://github.com/mapbox/mason/issues/396) - mason-js. This package makes installing packages seamless for node c++ addons. [Here’s an example](https://github.com/mapbox/node-cpp-skel/compare/proposed-mason-js-port#diff-8a4b16fa77ffdd0d617a663440578a2d) of how mason-js will be incorporated into the node-cpp-skel build system, as well as other node/cpp projects. 

# Phase 1
## Functionality 
- [x] Read  `mason-versions.ini` file in the project directory. This file declares C++ dependencies and versions.

 **example: mason-versions.ini** 

    [headers]
    protozero=1.5.1
    sparsepp=0.95
    [compiled]
    ccache=3.2.4

- [x] Install header only and precompiled packages. 
    - [x] Fetch from s3 over https (two separate paths for downloading depending on whether the package is header-only or precompiled). If you want to navigate to the mason bucket, it’s at `https://s3.amazonaws.com/mason-binaries/` 
- [x] Download packages into local directory structure
    - **Headers**: `./mason_packages/headers/{package}/{version}/<source files>`
      - e.g. `mason_packages/headers/vtzero/556fac5/include/vtzero/vector_tile.hpp`
    - **Binaries**: `./mason_packages/{platform}-{arch}/{package}/{version}/<files>`
      - e.g. `mason_packages/osx-x86_64/gdal/2.2.1/bin/ogr2ogr`
- [x] Symlink each package’s files in `./mason_packages/.link/<files>`
  - e.g. `mason_packages/.link/lib/libpng.a`
- [x] Install a single package**
  - `mason-js <package name>` installs package version as a single package

## Platforms

We’ve created a docker image and enabled travis to easily test linux and mac platforms. We’ve enabled appveyor for windows testing out of the box

- [x] Linux (x86_64) (debian, centos, amazon-linux)
  - [x] Enable travis 
  - [x] Create docker image
- [x] OS X (x86_64)
  - [x] Enable travis 
- [ ] Windows 
  - [x] Enable appveyor for windows testing out of the box. 
# Phase II 

Possibilities are endless…! Consider: usefulness, feasibility, sustainability to maintain, and set of questions/next steps. Goal is to understand the potential and actual mason-js roadmap. 

If we have this problem, but a custom solution isn't feasible, what is? 

- [ ] Create spreadsheet of obvious package management solutions while considering roadmap. 

## Functionality

**Versioning** 
Adding the ability to `^` carrot or `~`, similar to package.json dependencies in `mason-versions.ini`. 

**Global Installs**
Adding a [global] header to `mason-versions.ini` for any packages that should installed globally. 

Or something like:  
`mason-js install -g tippecanoe 1.16.9`

**Validate package dependency versions match** 
Original ticket here: https://github.com/mapbox/mason/issues/403

C/C++ can’t have duplicate versions of the same module. One idea - if packages don’t match, stop downloading from S3 and introduce fatal error. We could continue collecting all packages that are clashing and then display all clashing package versions to the user.  “Bad news for you. You have two versions of protozero (1.5.2 and 1.5.1) and you should only have one.”

**List all available version of a package**
`mason-js info protozero` returns a list of all versions available, ie 1.5.1, 1.5.2. 

**Releases package TO S3**
`mason-js publish-internal` creates a dev release in the mason-binaries bucket?

## Supported Platforms
- Android (arm-v8,  arm-v7,  arm-v5, x86,  x86-64, mips, mips-64
- iOS simulator (i386, x86_64)
- iOS (armv7 arm64)
